const LITO_CHAT_CONFIG={enabled:true,supabaseUrl:"https://irdbpnzwqlxniswhwada.supabase.co",publishableKey:"sb_publishable_bRG--fNRut5x43Wqa9oFFA_ffe9gxrG",storageKey:"lito-tech-chat-session-v3"};
const el=(tag,className,text)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node};
const emptySession=()=>({conversationId:"",visitorToken:"",visitorName:"",visitorEmail:"",messages:[]});
const loadSession=()=>{try{return{...emptySession(),...JSON.parse(localStorage.getItem(LITO_CHAT_CONFIG.storageKey)||"{}")}}catch{return emptySession()}};
const saveSession=state=>localStorage.setItem(LITO_CHAT_CONFIG.storageKey,JSON.stringify(state));
const rpc=async(name,params)=>{const response=await fetch(LITO_CHAT_CONFIG.supabaseUrl+"/rest/v1/rpc/"+name,{method:"POST",cache:"no-store",headers:{"Content-Type":"application/json",apikey:LITO_CHAT_CONFIG.publishableKey,Authorization:"Bearer "+LITO_CHAT_CONFIG.publishableKey},body:JSON.stringify(params)});const text=await response.text();if(!response.ok)throw Error(text||"The chat service returned an error.");return text?JSON.parse(text):[]};
function boot(){if(!LITO_CHAT_CONFIG.enabled)return;let state=loadSession();const shell=el("div","custom-chat"),launcher=el("button","custom-chat-launcher","Chat"),panel=el("section","custom-chat-panel"),header=el("header","custom-chat-header"),headerText=el("strong","custom-chat-title","Chat with Lito Tech"),close=el("button","custom-chat-close","×"),body=el("div","custom-chat-body"),status=el("p","custom-chat-status","Send us a message and our reply will appear here."),transcript=el("div","custom-chat-transcript"),form=el("form","custom-chat-form"),name=document.createElement("input"),email=document.createElement("input"),message=document.createElement("textarea"),actions=el("div","custom-chat-actions"),send=el("button","button button-primary custom-chat-submit","Send message"),restart=el("button","button button-secondary","Start new chat"),feedback=el("p","custom-chat-feedback");
launcher.type="button";close.type="button";restart.type="button";send.type="submit";name.required=email.required=message.required=true;name.placeholder="Your name";email.type="email";email.placeholder="you@example.com";message.placeholder="Tell us what you need help with";message.rows=4;name.value=state.visitorName;email.value=state.visitorEmail;
const field=(label,input)=>{const wrapper=el("label","custom-chat-field");wrapper.append(el("span","custom-chat-field-label",label),input);return wrapper};
const render=()=>{transcript.innerHTML="";state.messages.forEach(item=>{const bubble=el("article","custom-chat-bubble custom-chat-bubble-"+(item.sender==="visitor"?"visitor":"support"));bubble.append(el("p","",item.text),el("span","custom-chat-meta",(item.sender==="visitor"?"You":"Lito Tech")+" · "+new Date(item.createdAt).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})));transcript.append(bubble)});transcript.scrollTop=transcript.scrollHeight};
const refresh=async()=>{if(!state.conversationId||!state.visitorToken)return;try{const rows=await rpc("get_visitor_chat_messages",{p_conversation_id:state.conversationId,p_visitor_token:state.visitorToken});state.messages=rows.map(row=>({sender:row.sender_type,text:row.message,createdAt:row.created_at}));saveSession(state);render();feedback.textContent=""}catch(error){console.warn("Chat refresh failed",error);feedback.textContent="Your message is saved. Checking for a reply…";feedback.dataset.state="error"}};
const open=()=>{shell.classList.add("is-open");refresh()};
launcher.onclick=()=>shell.classList.contains("is-open")?shell.classList.remove("is-open"):open();close.onclick=()=>shell.classList.remove("is-open");
restart.onclick=()=>{state=emptySession();localStorage.removeItem(LITO_CHAT_CONFIG.storageKey);name.value="";email.value="";message.value="";feedback.textContent="A new chat is ready.";feedback.dataset.state="success";render();message.focus()};
form.onsubmit=async event=>{event.preventDefault();const text=message.value.trim();if(!text)return;send.disabled=true;feedback.textContent="Sending…";try{if(!state.conversationId){const created=await rpc("start_chat_conversation",{p_visitor_name:name.value.trim(),p_visitor_email:email.value.trim(),p_source_page:location.href,p_message:text});const conversation=created[0];if(!conversation?.conversation_id||!conversation?.visitor_token)throw Error("The chat conversation could not be created.");state={conversationId:conversation.conversation_id,visitorToken:conversation.visitor_token,visitorName:name.value.trim(),visitorEmail:email.value.trim(),messages:[]}}else await rpc("send_visitor_chat_message",{p_conversation_id:state.conversationId,p_visitor_token:state.visitorToken,p_message:text});state.messages.push({sender:"visitor",text,createdAt:new Date().toISOString()});saveSession(state);render();message.value="";feedback.textContent="Message sent. We will reply here.";feedback.dataset.state="success";refresh()}catch(error){console.error("Chat submission failed",error);feedback.textContent="Message not sent: "+error.message;feedback.dataset.state="error"}finally{send.disabled=false}};
header.append(headerText,close);actions.append(send,restart);form.append(field("Name",name),field("Email",email),field("Message",message),actions,feedback);body.append(status,transcript,form);panel.append(header,body);shell.append(panel,launcher);document.body.append(shell);render();setInterval(refresh,5000)}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",boot,{once:true}):boot();